INSERT INTO ASSIGNMENTS (TITLE, DESCRIPTION, DUE_DATE, STUDENT_ID)
VALUES ('LAB7 POSTGRES', 'SET UP A DATABASE AND INSERT RECORDS AS DESCRIBED IN THE INSTRUCTIONS.', '2025-02-28', 1);

SELECT *
FROM STUDENTS;

SELECT * FROM ASSIGNMENTS, STUDENTS WHERE ASSIGNMENTS.STUDENT_ID = STUDENTS.STUDENT_ID;